name: Build Python 3.13 for Termux (aarch64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential wget curl \
            libffi-dev libbz2-dev libssl-dev libreadline-dev \
            zlib1g-dev libsqlite3-dev tk-dev libncursesw5-dev \
            xz-utils llvm libgdbm-dev libnss3-dev uuid-dev \
            crossbuild-essential-arm64

      - name: Run build script
        run: bash build.sh

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: python3.13-deb
          path: python3.13_3.13.0.deb
