name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '3.*'
  pull_request:
    branches:
      - main
      - '3.*'

jobs:
  build-android:
    name: Android (aarch64)
    runs-on: macos-14
    timeout-minutes: 60
    steps:
      # Clone python/cpython branch 3.13
      - name: Clone python/cpython branch 3.13
        run: |
          sudo sh -c 'echo "export CC=clang; export CXX=clang++" >> /etc/profile' && source /etc/profile
          git clone --branch 3.13 --depth 1 https://github.com/python/cpython.git cpython-3.13
          ls cpython-3.13

      # Build using the Android directory inside cpython-3.13
      - name: Build and test
        working-directory: ./cpython-3.13/Android
        run: ./android.py ci aarch64-linux-android

      # Package as .deb
      - name: Create Debian package
        working-directory: .
        run: |
          PKG_NAME="pyv313"
          PKG_VERSION="3.13"
          ARCH="arm64"
          DEB_DIR="$PKG_NAME"
          BUILD_DIR="./cpython-3.13/cross-build/aarch64-linux-android"

          mkdir -p $DEB_DIR/DEBIAN

          cat > $DEB_DIR/DEBIAN/control <<EOF
          Package: $PKG_NAME
          Version: $PKG_VERSION
          Architecture: $ARCH
          Maintainer: Cross-compiled by Shoaib Hassan
          Description: Python 3.13 cross-compiled for Termux aarch64
          EOF

          cat > $DEB_DIR/DEBIAN/postinst <<'EOF'
          #!/bin/sh
          set -e
          echo "pyv313 installed successfully!"
          exit 0
          EOF
          chmod 755 $DEB_DIR/DEBIAN/postinst

          # Copy built files — try prefix, else fallback to install
          if [ -d "$BUILD_DIR/prefix" ]; then
            cp -r $BUILD_DIR/prefix/* $DEB_DIR/usr/
          elif [ -d "$BUILD_DIR/install" ]; then
            cp -r $BUILD_DIR/install/* $DEB_DIR/usr/
          else
            ls $BUILD_DIR
            echo "No prefix/ or install/ directory found in $BUILD_DIR"
            exit 1
          fi

          dpkg-deb --build $DEB_DIR ${PKG_NAME}_${PKG_VERSION}_${ARCH}.deb

      # Upload the .deb as an artifact
      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: pyv313-deb
          path: pyv313_3.13_arm64.deb
          if-no-files-found: error
