name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "3.*"

jobs:
  build-android:
    runs-on: macos-14
    env:
      ANDROID_ARCH: aarch64
      PREFIX: ${{ github.workspace }}/prefix
      CC: clang
      CXX: clang++
      LD: clang
      AR: llvm-ar
      AS: llvm-as
      RANLIB: llvm-ranlib
      STRIP: llvm-strip
      PATH: /opt/homebrew/opt/llvm@21/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Homebrew dependencies
        run: |
          brew install llvm@21 lld cmake ninja unzip curl xz pkg-config

      - name: Prepare directories
        run: |
          mkdir -p $PREFIX

      - name: Install bzip2
        run: |
          curl -L -o bzip2-1.0.8-3.tar.gz https://github.com/beeware/cpython-android-source-deps/releases/download/bzip2-1.0.8-3/bzip2-1.0.8-3-aarch64-linux-android.tar.gz
          tar -xzf bzip2-1.0.8-3.tar.gz -C $PREFIX

      - name: Install xz
        run: |
          curl -L -o xz-5.4.6-1.tar.gz https://github.com/beeware/cpython-android-source-deps/releases/download/xz-5.4.6-1/xz-5.4.6-1-aarch64-linux-android.tar.gz
          tar -xzf xz-5.4.6-1.tar.gz -C $PREFIX

      - name: Install prebuilt zlib
        run: |
          curl -L -o zlib-prebuilt.zip https://github.com/Aasyaco/Some-help/actions/runs/17937181821/artifacts/4079476254
          unzip zlib-prebuilt.zip
          tar -xzf zlib-aarch64-android.tar.gz -C $PREFIX

      - name: Configure environment
        run: |
          echo "LDFLAGS=-L$PREFIX/bzip2-1.0.8-3/lib -L$PREFIX/xz-5.4.6-1/lib -L$PREFIX/zlib-aarch64-android/lib -L$PREFIX/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$PREFIX/bzip2-1.0.8-3/include -I$PREFIX/xz-5.4.6-1/include -I$PREFIX/zlib-aarch64-android/include -I$PREFIX/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$PREFIX/bzip2-1.0.8-3/lib/pkgconfig:$PREFIX/xz-5.4.6-1/lib/pkgconfig:$PREFIX/zlib-aarch64-android/lib/pkgconfig:$PREFIX/lib/pkgconfig" >> $GITHUB_ENV

      - name: Clone CPython
        run: |
          git clone --branch 3.13 --depth 1 https://github.com/python/cpython.git cpython-3.13
          cp android.py cpython-3.13/Android/android.py

      - name: Clean previous build
        working-directory: ./cpython-3.13/Android
        run: |
          python3.11 ./android.py clean $ANDROID_ARCH-linux-android || true

      - name: Build CPython
        working-directory: ./cpython-3.13/Android
        run: |
          python3.11 ./android.py ci $ANDROID_ARCH-linux-android

      - name: Package as .deb
        run: |
          PKG_NAME="pyv313"
          PKG_VERSION="3.13"
          ARCH="aarch64"
          DEB_DIR="$PKG_NAME"
          BUILD_DIR="./cpython-3.13/cross-build/$ARCH-linux-android"

          mkdir -p $DEB_DIR/DEBIAN
          mkdir -p $DEB_DIR/usr

          cat > $DEB_DIR/DEBIAN/control <<EOF
          Package: $PKG_NAME
          Version: $PKG_VERSION
          Architecture: $ARCH
          Maintainer: Cross-compiled by GitHub Actions
          Description: Python 3.13 cross-compiled for Termux aarch64
          EOF

          cat > $DEB_DIR/DEBIAN/postinst <<'EOF'
          #!/bin/sh
          set -e
          echo "pyv313 installed successfully!"
          exit 0
          EOF
          chmod 755 $DEB_DIR/DEBIAN/postinst

          if [ -d "$BUILD_DIR/prefix" ]; then
            cp -r $BUILD_DIR/prefix/* $DEB_DIR/usr/
          elif [ -d "$BUILD_DIR/install" ]; then
            cp -r $BUILD_DIR/install/* $DEB_DIR/usr/
          else
            ls $BUILD_DIR
            echo "No prefix/ or install/ directory found in $BUILD_DIR"
            exit 1
          fi

          dpkg-deb --build $DEB_DIR ${PKG_NAME}_${PKG_VERSION}_${ARCH}.deb

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: pyv313
          path: pyv313_3.13_aarch64.deb
          if-no-files-found: error
