name: Build Android Python

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android-build:
    runs-on: macos-latest
    env:
      ANDROID_HOME: ${{ runner.temp }}/android-sdk
      ANDROID_NDK_HOME: ${{ runner.temp }}/android-sdk/ndk/r28c
      PATH: ${{ runner.temp }}/android-sdk/cmdline-tools/latest/bin:${{ runner.temp }}/android-sdk/platform-tools:${{ runner.temp }}/android-sdk/ndk/r28c:$PATH

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure Python 3
        run: |
          python3 --version
          python3 -m ensurepip
          python3 -m pip install --upgrade pip setuptools wheel

      - name: Setup Android SDK & NDK r28c
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -L https://dl.google.com/android/repository/commandlinetools-mac-9477386_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools latest
          rm cmdline-tools.zip

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "ndk;28.0.3"

      - name: Build Python for Android
        run: |
          cd Android
          python3 android.py ci aarch64-linux-android --clean -- -enable-optimizations
          
