name: Build Python 3.13.3 DEB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget tar clang make libssl-dev libffi-dev zlib1g-dev dpkg-dev xz-utils git

      - name: Run build.sh
        run: ./build.sh

      - name: Upload built .deb package
        uses: actions/upload-artifact@v4
        with:
          name: python3.13.deb
          path: python3.13_*.deb
          
